import { yupResolver } from '@hookform/resolvers/yup'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Router from 'next/router'
import { useEffect, useState } from 'react'
import { useForm, SubmitHandler } from 'react-hook-form'
import { toast } from 'react-toastify'
import * as yup from 'yup'

import { Button, Input, Section } from '../../components'
import { Checkbox } from '../../components/atoms/Checkbox'
import {
  createUser,
  currentUserSelector,
  userSelector,
} from '../../store/features/user'
import { useAppDispatch, useAppSelector } from '../../store/hooks'

const schema = yup.object({
  username: yup.string().required(),
  email: yup.string().email(),
  password: yup.string().required('Password is required'),
  confirmPassword: yup
    .string()
    .oneOf([yup.ref('password')], 'Password must match'),
})

type FormData = yup.InferType<typeof schema>

export default function SignUp() {
  const dispatch = useAppDispatch()
  const { signUpState } = useAppSelector(userSelector)
  const [isShowPassword, setIsShowPassword] = useState<boolean>(false)
  const currentUser = useAppSelector(currentUserSelector)
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<FormData>({
    resolver: yupResolver(schema),
  })

  const onSignUp: SubmitHandler<FormData> = (data) => {
    if (data.password === data['confirmPassword']) {
      dispatch(
        createUser({
          username: data.username,
          password: data.password,
          email: data.email,
        }),
      )
    }
  }

  const onPerformSignUp = () => {
    if (signUpState.status === 'success') {
      toast.success('Sign Up success')
      Router.push('/signin')
    } else if (signUpState.status === 'error') {
      toast.error('Sign up fail')
    }
  }

  const onSignedIn = () => {
    if (currentUser !== null) {
      Router.push('/')
    }
  }

  useEffect(onPerformSignUp, [signUpState])
  useEffect(onSignedIn, [currentUser])

  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section className="container mx-auto flex flex-col gap-y-8 md:flex-row md:gap-x-8">
        <>
          <div className="hidden grow-[2] md:block">
            <Image src="/people.svg" height={400} width={600} alt="people" />
          </div>
          <div className="flex grow-[1] flex-col gap-y-8">
            <h1 className="text-4xl font-bold">Sign Up</h1>
            <form
              onSubmit={handleSubmit(onSignUp)}
              className="flex flex-col gap-y-3">
              <Input label="username" {...register('username')} />
              <Input label="email" type="email" {...register('email')} />
              <Input
                label="password"
                type={isShowPassword ? 'text' : 'password'}
                {...register('password')}
              />
              <Input
                label="confirm password"
                type={isShowPassword ? 'text' : 'password'}
                errorMessage={errors?.confirmPassword?.message}
                {...register('confirmPassword')}
              />
              <Checkbox
                label="show password"
                onChange={() => setIsShowPassword((prev) => !prev)}
              />
              <Button type="submit">submit</Button>
            </form>
            <p className="text-sm text-gray-500">
              Already have an account?&nbsp;
              <Link href={'/signin'} className="font-bold text-black underline">
                Sign-in
              </Link>
            </p>
          </div>
        </>
      </Section>
    </>
  )
}
