import Head from 'next/head'
import { useEffect } from 'react'

import {
  APODSection,
  Loading,
  MoonPhaseSection,
  WeatherSection,
  UpcomingSection,
} from '../components'
import { feedSelector, fetchFeedContent } from '../store/features/feed'
import { useAppDispatch, useAppSelector } from '../store/hooks'

export default function Home() {
  const dispatch = useAppDispatch()
  const { weather, moonPhase, apod, loadContentState } =
    useAppSelector(feedSelector)

  useEffect(() => {
    dispatch(fetchFeedContent())
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="mb-4 text-3xl font-bold capitalize">welcome</h1>
      <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
        {loadContentState.status === 'success' ? (
          <>
            <UpcomingSection />
            {weather ? <WeatherSection content={weather} /> : <Loading />}
            {moonPhase ? <MoonPhaseSection content={moonPhase} /> : <Loading />}
            {apod ? <APODSection content={apod} /> : <Loading />}
          </>
        ) : (
          <div className="grid-span-3">
            <Loading />
          </div>
        )}
      </div>
    </>
  )
}
