import Head from 'next/head'
import { useEffect } from 'react'

import {
  APODSection,
  MoonPhaseSection,
  WeatherSection,
  UpcomingSection,
  TelescopeSection,
  TargetSection,
  ForecastSection,
} from '../components'
import {
  feedSelector,
  fetchFeedContent,
  fetchWeather,
} from '../store/features/feed'
import { useAppDispatch, useAppSelector } from '../store/hooks'

export default function Home() {
  const dispatch = useAppDispatch()
  const { forecastData, moonPhase, apod } = useAppSelector(feedSelector)

  useEffect(() => {
    dispatch(fetchFeedContent())
    dispatch(fetchWeather({}))
  }, [])

  return (
    <>
      <Head>
        <title>DooDaoMa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="mb-4 text-3xl font-bold capitalize">welcome</h1>
      <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
        <UpcomingSection />
        <WeatherSection content={forecastData} />
        <div className="row-span-3 flex flex-col gap-y-8">
          <MoonPhaseSection content={moonPhase} />
          <TelescopeSection />
        </div>
        <APODSection content={apod} />
        <TargetSection />
        <ForecastSection content={forecastData} />
      </div>
    </>
  )
}
