import Head from 'next/head'

import { Loading } from '../../components'
import { ImagingWebSocket } from '../../components/organisms/ImagingWebSocket'
import { userSelector } from '../../store/features/user'
import { useAppSelector } from '../../store/hooks'

export default function Imaging() {
  const { currentUser } = useAppSelector(userSelector)

  return (
    <>
      <Head>
        <title>Imaging</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentUser !== null ? (
        <ImagingWebSocket userId={currentUser.id} />
      ) : (
        <Loading />
      )}
    </>
  )
}

Imaging.requireAuth = true
